name: Build Android
run-name: Creating Production Ready Android App 🚀
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Check folder
        run: ls ./android  
        
      - name: Download app-config
        run: curl https://beta-unite.3shape.com/app-config.json            

      - name: Download app-config and store
        run: curl -o .src/app-config.json https://beta-unite.3shape.com/app-config.json 
              
      - name: Check folder
        run: ls ./src  
        
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: install dependencies
        run: npm ci

      - name: Create Build Folder
        run: npm run build

      # - name: Add android folder if not present
      #   run: if [ ! -d "./android" ]; then npx cap add android; fi

      - name: Capacitor sync
        run: npx cap sync

      # - name: Capacitor update
      #   run: npx cap update

      # - name: Capacitor copy
      #   run: npx cap copy
      
      # TODO: Check for folder structure in README for generating splash screen 
      # - name: Generate icons and splash screen to android folder 
      #   run:  if [ -d "./resources" ]; then npm install @capacitor/assets --save-dev && npx capacitor-assets generate --android; fi
        
      # - name: Build app bundle
      #   run: cd android && ./gradlew bundle && ./gradlew assembleDebug

      - name: Sign dev build
        run: npx cap build android --androidreleasetype=AAB --keystorealias="${{ secrets.RELEASE_KEYSTORE_ALIAS }}" --keystorealiaspass="${{ secrets.RELEASE_KEYSTORE_ALIAS_PASSWORD }}" --keystorepass="${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" --keystorepath="${{ secrets.RELEASE_KEYSTORE }}"

      - name: Distribute to AppCenter
        # You may pin to the exact commit or the version.
        # uses: wzieba/AppCenter-Github-Action@70e33d4842b97b381833ad5c9c93a562b39d5d9f
        uses: wzieba/AppCenter-Github-Action@v1.3.4
        with:
          # App name followed by username e.g. wzieba/Sample-App
          appName: sashgo/Capacitor
          # Upload token - you can get one from appcenter.ms/settings
          token: ${{ secrets.APP_CENTER_TOKEN }}
          # Distribution group
          group: Mobile
          # Artefact to upload (.apk or .ipa)
          file: /home/runner/work/Capacitor/Capacitor/android/app/build/outputs/bundle/release/app-release-signed.aab
          # # Build version parameter required for .zip, .msi, .pkg and .dmg files
          # buildVersion: # optional
          # # Build number parameter required for macOS .pkg and .dmg files
          # buildNumber: # optional
          # # Release notes visible on release page
          # releaseNotes: # optional
          # # Generate release notes based on the latest git commit
          # gitReleaseNotes: # optional
          # # If true, send an email notification to the distribution group
          # notifyTesters: # optional
          # # If true, shows additional information from the action execution
          # debug: # optional
