name: Build iOS
run-name: Creating Production Ready iOS App 🚀
on:
  push:
    branches: [ "Actions_ios" ]
  workflow_dispatch:

jobs:
  build:
    name: Build IPA
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: Actions_ios
