name: Build iOS
run-name: Creating Production Ready iOS App 🚀
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build IPA
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: Actions_ios

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
          
      - name: Create Build Folder
        run: npm run build

      - name: Add ios folder if not present
        run: if [ ! -d "./ios" ]; then npx cap add ios; fi

      - name: Capacitor sync
        run: npx cap sync

      - name: Capacitor update
        run: npx cap update

      - name: Capacitor copy
        run: npx cap copy

        
